In [105]:
import pandas as pd

In [49]:
def add_o(v):
    # type(v) == str checks if v is a string
    s = f'.oO{v}Oo.' if type(v) == str else v
    return s
def fancify_it(plain):
    def fancy(*args):
        modified = [add_o(a) for a in args]
        plain(*modified)
    return fancy
@fancify_it
def wat(a, b):
    print(a)
    print(b)
    
wat('hi', 1)

.oOhiOo.
1


In [151]:
class Image:
    def __init__(self, pixels):
        self.pixels = pixels
    def __getitem__(self,t):
        x, y = t
        return self.pixels[x][y]

    def __setitem__(self, t, v):
        x, y = t
        self.pixels[x][y] = v
    
    def dim(self):
        return len(self.pixels[0]), len(self.pixels)

In [152]:
 img = Image([
       [(255, 255, 255), (  0,   0,   0), (100, 200,   0)],
       [(  0, 100,   0), (  0,  77,  77), (123, 123, 123)],
   ])

In [153]:
print(img[1,2])

(123, 123, 123)


In [154]:
img[0, 1] = (1, 1, 1)

In [155]:
print(img[0,1])

(1, 1, 1)


In [156]:
 img1 = Image([
       [(255, 255, 255), (  0,   0,   0)],
       [(  0, 100,   0), (  0,  77,  77)],
   ])

In [90]:
print(img1.dim())

(2, 2)


In [60]:
class Building(object):
    def __init__(self, floors):
         self._floors = [None]*floors
    def occupy(self, floor_number, data):
          self._floors[floor_number] = data
    def get_floor_data(self, floor_number):
          return self._floors[floor_number]

building1 = Building(4) # Construct a building with 4 floors
building1.occupy(0, 'Reception')
building1.occupy(1, 'ABC Corp')
building1.occupy(2, 'DEF Inc')
print( building1.get_floor_data(2) )

DEF Inc


In [63]:
class Building(object):
    def __init__(self, floors):
         self._floors = [None]*floors
    def __setitem__(self, floor_number, data):
          self._floors[floor_number] = data
    def __getitem__(self, floor_number):
          return self._floors[floor_number]

building1 = Building(4) # Construct a building with 4 floors
print(list(building1))
building1[0] = 'Reception'
building1[1] = 'ABC Corp'
building1[2] = 'DEF Inc'
print( building1[2] )

[None, None, None, None]
DEF Inc


In [78]:
s = (1,3)

In [79]:
type(s)

tuple

In [23]:
x = 3 

In [26]:
template = "{0:.2f} Argentine Pesos are worth US ${1:d}".format(4.5560, 1)

In [27]:
template

'4.56 Argentine Pesos are worth US $1'

In [28]:
tuple = (4,5,6)
x,y,z = tuple 

In [29]:
x 

4

In [30]:
z

6

In [31]:
values = 1,2,3,4,5

In [32]:
a,b,*rest = values 

In [33]:
rest

[3, 4, 5]

In [34]:
a

1

In [35]:
a,b

(1, 2)

In [36]:
a = list(tuple)

In [37]:
a

[4, 5, 6]

In [47]:
t = (1, 6, 2)
for i in range(*t):
    print(i)

1
3
5


In [62]:
t = (1,6,2)
print(list(range(1, 6, 2)))

[1, 3, 5]


# 

In [66]:
import numpy as np
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [68]:
a.shape

(2, 2, 2)

In [69]:
a2 = np.array([[[8, 9]], [[88, 99]]])

In [71]:
a2.shape

(2, 1, 2)

In [72]:
b = np.arange(36).reshape((4, 3, 3))

In [73]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [82]:
b[:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [85]:
b.shape

(4, 3, 3)

In [88]:
c = np.arange(9).reshape(3,3)

In [90]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
c[:,2:]

array([[2],
       [5],
       [8]])

In [94]:
d = np.arange(24).reshape((3, 4, 2))

In [95]:
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [96]:
d[:2, [False, True, False, True], 1:]

array([[[ 3],
        [ 7]],

       [[11],
        [15]]])

In [97]:
d[:2, [False, True, False, True], -1]

array([[ 3,  7],
       [11, 15]])

In [98]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
c[[2,1]]

array([[6, 7, 8],
       [3, 4, 5]])

In [103]:
c[[0, 1, 2]]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
s = pd.Series([1, 2], ['x', 'y'])

In [112]:
s  == pd.Series([1], ['x'])

ValueError: Can only compare identically-labeled Series objects

In [113]:
df = pd.DataFrame([[4, 5, 6], [7, 8, 9]],
	columns=['foo', 'bar', 'baz'])

In [114]:
df

foo  bar  baz
0    4    5    6
1    7    8    9

In [115]:
df[['bar','bar']]

bar  bar
0    5    5
1    8    8

In [118]:
from pandas import Series
s = Series(data=['foo', 'bar', 'baz', 'qux', 'quxx', 'corge'],
           index=['ant', 'bat', 'cat', 'good doge', 'eel', 'fly'])

In [126]:
max([len(label) for label in s.index])

9